schema_version = "1.0.0"
id = "witcher3_tools"
version = "1.1.0"
name = "Witcher 3 Tools"
tagline = "Import and export Witcher assets"
maintainer = "Dingdio"
type = "add-on"
blender_version_min = "4.5.0"
platforms = ["windows-x64"]
license = ["SPDX:GPL-3.0-or-later"]
website = "https://github.com/dingdio/Witcher3_Blender_Tools"
wheels = [
  "wheels/colorama-0.4.6-py2.py3-none-any.whl",
  "wheels/cramjam-2.9.1-cp311-cp311-win_amd64.whl",
  "wheels/cramjam-2.9.1-cp313-cp313-win_amd64.whl",
  "wheels/h5py-3.16.0-cp311-cp311-win_amd64.whl",
  "wheels/h5py-3.16.0-cp313-cp313-win_amd64.whl",
  "wheels/platformdirs-4.9.6-py3-none-any.whl",
  "wheels/pywhispercpp-1.4.1-cp311-cp311-win_amd64.whl",
  "wheels/pywhispercpp-1.4.1-cp313-cp313-win_amd64.whl",
  "wheels/tqdm-4.67.3-py3-none-any.whl",
]

[permissions]
files = "Read game data and write caches/exports"
network = "Read the local REDkit debug service"

[build]
paths_exclude_pattern = [
  "__pycache__/",
  ".*",
  "*.zip",
  "dev/dev_config.json",
  "wheels/certifi-*",
  "wheels/charset_normalizer-*",
  "wheels/cramjam-*-cp310-*",
  "wheels/idna-*",
  "wheels/numpy-*",
  "wheels/requests-*",
  "wheels/urllib3-*",
]
